[workspace]
resolver = "2"
members = [
    "virtual-display-driver",
    "wdf-umdf-sys",
    "wdf-umdf",
    "winlog",
    "driver-ipc",
]

[profile.release]
strip = true
codegen-units = 1
lto = true
