[env]
BUILD_TARGET_PATH = { script = ['''
    for /f "tokens=*" %%a in ('cargo target-dir') do set target_dir=%%a

    echo %target_dir%
'''] }

[env.prod]
PROD = "1"
PROFILE = "-p prod"
BUILD_FLAGS = "--release"

[tasks.tests]
script = ['''
cd virtual-display-driver
cargo target-dir
''']

[tasks.build]
clear = true
script = [
    # build virtual-display-driver
    "cargo make %PROFILE% --cwd virtual-display-driver build",
    # copy all files to single output directory
    "cargo make %PROFILE% --cwd virtual-display-driver copy",
    # build the control app
    "cargo build -p virtual-display-driver-control %BUILD_FLAGS%",
    # copy all files to single output directory
    "cargo make %PROFILE% --cwd virtual-display-driver-control copy",
]

[tasks.build-installer]
dependencies = ["build"]
script = [
    # 999 represents dev build
    '''
    if defined RELEASE_VERSION (
        set release=-i %RELEASE_VERSION%
    ) else if not defined PROD (
        set release=-i 9.9.9
    )

    if not defined PROD (
        set mode=-d
    )

    del /S /Q /F target\output\*.msi

    cargo wix -p virtual-display-driver %release% %mode% --nocapture -I installer/main.wxs -o target\output
    ''',
]

[config]
default_to_workspace = false
