[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
BUILD_DLL_OLD_NAME = "virtual_display_driver.dll"
BUILD_DLL_NAME = "VirtualDisplayDriver.dll"

[env.dev]
# for developer inf stamping mode
PRIVATE_DRIVER_PACKAGE = "true"
TARGET_PATH = "debug"
CAT_FILE = "delta.cat"

[env.prod]
TARGET_PATH = "release"
BUILD_FLAGS = "--release"
CAT_FILE = "VirtualDisplayDriver.cat"

[tasks.set-build-path]
env = { "BUILD_TARGET_PATH" = { script = ['''
    if defined CARGO_TARGET_DIR (
        set "target_dir=%CARGO_TARGET_DIR%"
    ) else if defined CARGO_BUILD_TARGET_DIR (
        set "target_dir=%CARGO_BUILD_TARGET_DIR%"
    ) else (
        set "target_dir=target"
    )

    echo %target_dir%/%TARGET_PATH%
'''] } }

[tasks.build-driver]
dependencies = ["set-build-path"]
script = ["cargo b %BUILD_FLAGS% -p virtual-display-driver"]

[tasks.rename]
dependencies = ["build-driver"]
script = ['''
    cd /D %BUILD_TARGET_PATH%
    del  /f /q "%BUILD_DLL_NAME%"
    ren "%BUILD_DLL_OLD_NAME%" "%BUILD_DLL_NAME%"
    ''']

[tasks.stamp-inf]
dependencies = ["build-driver"]
script = [
    # Load the Visual Studio Developer environment
    "call \"%ProgramFiles%\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\"",

    # copy inf to target dir
    "copy /y VirtualDisplayDriver.inf \"%BUILD_TARGET_PATH%/VirtualDisplayDriver.inf\"",

    # Stamp inf
    "stampinf.exe -v \"%CARGO_MAKE_PROJECT_VERSION%\" -d * -a amd64 -u 2.15.0 -f \"%BUILD_TARGET_PATH%/VirtualDisplayDriver.inf\"",
]

[tasks.gen-cat]
dependencies = ["build-driver", "rename", "stamp-inf", "sign"]
script = [
    # Load the Visual Studio Developer environment
    '''
    REM Get vc env
    call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"

    REM generate cat file
    inf2cat /driver:%BUILD_TARGET_PATH% /os:10_x64

    signtool sign /a /fd SHA256 /v /s PrivateCertStore /n DriverCertificate /t http://timestamp.digicert.com "%BUILD_TARGET_PATH%/%CAT_FILE%"
    ''',
]

[tasks.sign]
dependencies = ["build-driver", "rename", "stamp-inf"]
script = [
    # Load the Visual Studio Developer environment
    "call \"%ProgramFiles%\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\"",

    # Create a self signed certificate (only if not already done)
    "if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer )",

    # Sign the driver
    "signtool sign /a /fd SHA256 /v /s PrivateCertStore /n DriverCertificate /t http://timestamp.digicert.com \"%BUILD_TARGET_PATH%/%BUILD_DLL_NAME%\"",
]

[tasks.build]
dependencies = ["build-driver", "rename", "sign", "stamp-inf", "gen-cat"]
clear = true

[config]
default_to_workspace = false
main_project_member = "virtual-display-driver"
