[build]
target = "x86_64-pc-windows-msvc"

rustflags = [
    "-Z",
    "pre-link-arg=/NOLOGO",
    "-Z",
    "pre-link-arg=/MANIFEST:NO",
    "-Z",
    "pre-link-arg=/SUBSYSTEM:WINDOWS",
    "-Z",
    "pre-link-arg=/DYNAMICBASE",
    "-Z",
    "pre-link-arg=/NXCOMPAT",

    "-C",
    "link-arg=/OPT:REF,ICF",
]
