[build]
target = "x86_64-pc-windows-msvc"

rustflags = [
    # our driver entry point fn
    "-C",
    "link-arg=/ENTRY:DriverEntry",
    # statically link msvcrt
    "-C",
    "target-feature=+crt-static",
    # Specifies that the digital signature of the binary image must be checked at load time.
    "-C",
    "link-arg=/INTEGRITYCHECK",
]
