[package]
name = "wdf-umdf-sys"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
paste = "1.0.14"
bytemuck = "1.14.0"
thiserror = "1.0.49"

[build-dependencies]
bindgen = "0.69.1"
thiserror = "1.0.49"
winreg = "0.51.0"
