name: Build App

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions: write-all
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ github.event_name == 'release' && 'app-release' || 'app-dev' }}

      - name: Build App
        env:
          RELEASE: ${{ github.event_name == 'release' && '--release' || '' }}
        run: cargo build $env:RELEASE -p virtual-display-driver-control

      - name: Upload Artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with:
          name: driver
          path: |
            target/debug/*.exe

      - name: Attach assets to release
        if: github.event_name == 'release'
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/release/virtual-display-driver-control.exe"
          draft: false
          release_id: ${{ github.event.release.id }}
