name: Clippy

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: windows-2022
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Clippy Component
        run: rustup component add clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: -- -Dwarnings
